DELETE FROM cart_items;
DELETE FROM reviews;
DELETE FROM products;
DELETE FROM categories;

INSERT INTO categories (id, name, slug, description, image_url) VALUES
  (gen_random_uuid(), '3-in-1 Charging Stations', '3-in-1-charging-stations', 'Charge your phone, watch, and earbuds all at once.', 'https://images.pexels.com/photos/4041178/pexels-photo-4041178.jpeg?auto=compress&cs=tinysrgb&w=600'),
  (gen_random_uuid(), 'GaN Fast Chargers', 'gan-fast-chargers', 'Next-gen gallium nitride chargers for blazing fast speeds.', 'https://images.pexels.com/photos/4202315/pexels-photo-4202315.jpeg?auto=compress&cs=tinysrgb&w=600'),
  (gen_random_uuid(), 'Magnetic Wireless Chargers', 'magnetic-wireless-chargers', 'Snap-on magnetic wireless chargers for effortless power.', 'https://images.pexels.com/photos/4218883/pexels-photo-4218883.jpeg?auto=compress&cs=tinysrgb&w=600'),
  (gen_random_uuid(), 'USB-C Charging Hubs', 'usb-c-charging-hubs', 'Expand one port into many with power and data.', 'https://images.pexels.com/photos/4792728/pexels-photo-4792728.jpeg?auto=compress&cs=tinysrgb&w=600'),
  (gen_random_uuid(), 'Travel Charging Kits', 'travel-charging-kits', 'All-in-one kits for charging on the go.', 'https://images.pexels.com/photos/4792728/pexels-photo-4792728.jpeg?auto=compress&cs=tinysrgb&w=600'),
  (gen_random_uuid(), 'MagSafe Accessories', 'magsafe-accessories', 'Rings, mounts, and add-ons for your MagSafe ecosystem.', 'https://images.pexels.com/photos/4792728/pexels-photo-4792728.jpeg?auto=compress&cs=tinysrgb&w=600');

INSERT INTO products (id, name, description, price, compare_price, category, subcategory, image_url, rating, review_count, stock, sku, featured, best_seller, tags, specs) VALUES
  (gen_random_uuid(), 'Anker 3-in-1 Cube with MagSafe', 'Officially Apple-certified 3-in-1 charging station for iPhone, Apple Watch, and AirPods. Compact foldable design perfect for travel. Adjustable 15W MagSafe charging for iPhone.', '18.99', '29.99', '3-in-1 Charging Stations', '3-in-1', 'https://images.pexels.com/photos/4041178/pexels-photo-4041178.jpeg?auto=compress&cs=tinysrgb&w=600', '4.9', 312, 89, 'CS-301-001', true, true, to_jsonb(ARRAY['magsafe','apple-certified','travel','compact']), '{"Color":"White","Input":"30W","MagSafe":"15W","Watch":"5W","AirPods":"5W"}'::jsonb),
  (gen_random_uuid(), 'UGREEN 3-in-1 Wireless Charger Stand', 'Magnetic charging station for iPhone, Watch, and earbuds. Strong N52 magnets align perfectly. Detachable Apple Watch charger for portable use.', '16.99', '24.99', '3-in-1 Charging Stations', '3-in-1', 'https://images.pexels.com/photos/4218883/pexels-photo-4218883.jpeg?auto=compress&cs=tinysrgb&w=600', '4.7', 189, 156, 'CS-301-002', true, false, to_jsonb(ARRAY['magnetic','stand','watch','detachable']), '{"Color":"Black","Input":"33W","iPhone":"15W","Watch":"5W","Earbuds":"5W"}'::jsonb),
  (gen_random_uuid(), 'Belkin 3-in-1 BoostCharge Pro', 'Premium 3-in-1 charging station with MagSafe 15W. Sleek minimalist design fits any desk. Apple Watch Series 9 and Ultra compatible.', '19.99', '34.99', '3-in-1 Charging Stations', '3-in-1', 'https://images.pexels.com/photos/4792728/pexels-photo-4792728.jpeg?auto=compress&cs=tinysrgb&w=600', '4.8', 245, 67, 'CS-301-003', false, true, to_jsonb(ARRAY['premium','magSafe','desk','apple-watch']), '{"Color":"White","MagSafe":"15W","Watch":"5W","AirPods":"5W"}'::jsonb),
  (gen_random_uuid(), 'Anker 735 Nano II 65W', 'Compact 65W GaN charger with 3 ports. Charges MacBook Air, iPhone, and Apple Watch simultaneously. 50% smaller than original 65W chargers.', '17.99', '27.99', 'GaN Fast Chargers', 'GaN', 'https://images.pexels.com/photos/4202315/pexels-photo-4202315.jpeg?auto=compress&cs=tinysrgb&w=600', '4.9', 578, 234, 'GFC-65W-001', true, true, to_jsonb(ARRAY['gan','65w','compact','3-port']), '{"Total Output":"65W","Ports":"3","USB-C1":"45W","USB-C2":"20W","USB-A":"18W"}'::jsonb),
  (gen_random_uuid(), 'UGREEN Nexode 100W GaN Charger', '4-port 100W GaN charger for high-power devices. Charge MacBook Pro, iPad, and two phones simultaneously. Advanced temperature control.', '19.99', '32.99', 'GaN Fast Chargers', 'GaN', 'https://images.pexels.com/photos/4218883/pexels-photo-4218883.jpeg?auto=compress&cs=tinysrgb&w=600', '4.8', 423, 178, 'GFC-100W-001', true, true, to_jsonb(ARRAY['gan','100w','4-port','macbook']), '{"Total Output":"100W","Ports":"4","USB-C1":"65W","USB-C2":"30W","USB-C3":"22.5W"}'::jsonb),
  (gen_random_uuid(), 'Baseus 65W GaN Mini Charger', 'Ultra-compact 65W GaN charger with foldable plug. 40% smaller than Apple charger. Intelligent power distribution for safe charging.', '15.99', '22.99', 'GaN Fast Chargers', 'GaN', 'https://images.pexels.com/photos/4792728/pexels-photo-4792728.jpeg?auto=compress&cs=tinysrgb&w=600', '4.7', 234, 289, 'GFC-65W-002', false, false, to_jsonb(ARRAY['gan','mini','foldable','65w']), '{"Color":"White","Output":"65W","Ports":"2","USB-C1":"45W","USB-C2":"20W"}'::jsonb),
  (gen_random_uuid(), 'Anker MagGo Magnetic Pad', 'Slim magnetic wireless charger for iPhone 12 and later. Perfect snap alignment with strong magnets. 15W charging with LED status indicator.', '14.99', '21.99', 'Magnetic Wireless Chargers', 'Magnetic', 'https://images.pexels.com/photos/4041178/pexels-photo-4041178.jpeg?auto=compress&cs=tinysrgb&w=600', '4.8', 345, 198, 'MWC-MAG-001', true, true, to_jsonb(ARRAY['magnetic','magsafe','slim','iphone']), '{"Color":"White","Output":"15W","Thickness":"7mm","Cable":"3ft"}'::jsonb),
  (gen_random_uuid(), 'Spigen Mag Fit Duo Pad', 'Magnetic wireless charger for iPhone and AirPods. Non-slip silicone base with elevated AirPods charging spot. LED charging indicator.', '13.99', '19.99', 'Magnetic Wireless Chargers', 'Magnetic', 'https://images.pexels.com/photos/4202315/pexels-photo-4202315.jpeg?auto=compress&cs=tinysrgb&w=600', '4.6', 167, 234, 'MWC-MAG-002', true, false, to_jsonb(ARRAY['magnetic','2-in-1','airpods','non-slip']), '{"Color":"Black","iPhone":"15W","AirPods":"5W","Base":"Silicone"}'::jsonb),
  (gen_random_uuid(), 'Anker MagGo Magnetic Stand', 'Magnetic wireless charging stand with adjustable angle. 360-degree rotation for portrait and landscape mode. 15W MagSafe compatible.', '16.99', '25.99', 'Magnetic Wireless Chargers', 'Magnetic', 'https://images.pexels.com/photos/4218883/pexels-photo-4218883.jpeg?auto=compress&cs=tinysrgb&w=600', '4.7', 234, 145, 'MWC-MAG-003', false, true, to_jsonb(ARRAY['stand','360','adjustable','magSafe']), '{"Color":"White","Output":"15W","Rotation":"360°","Angle":"0-60°"}'::jsonb),
  (gen_random_uuid(), 'Satechi USB-C 6-in-1 Hub', 'Expand your single USB-C port into 6 ports. 4K HDMI, USB-C PD pass-through, 3 USB-A ports, SD card reader. Aluminum unibody design.', '19.99', '29.99', 'USB-C Charging Hubs', 'Hub', 'https://images.pexels.com/photos/4792728/pexels-photo-4792728.jpeg?auto=compress&cs=tinysrgb&w=600', '4.8', 456, 112, 'HUB-6N1-001', true, true, to_jsonb(ARRAY['hdmi','4k','sd-card','aluminum']), '{"HDMI":"4K@60Hz","USB-C PD":"100W","USB-A":"3x 5Gbps","SD Card":"UHS-I"}'::jsonb),
  (gen_random_uuid(), 'Anker 555 USB-C Hub (8-in-1)', 'Ultimate USB-C hub with 8 ports. 4K HDMI, 100W PD, 2 USB-A, 1 USB-C, Ethernet, SD/TF card slots. Plug and play for MacBook and iPad.', '18.99', '28.99', 'USB-C Charging Hubs', 'Hub', 'https://images.pexels.com/photos/4041178/pexels-photo-4041178.jpeg?auto=compress&cs=tinysrgb&w=600', '4.7', 312, 167, 'HUB-8N1-001', true, false, to_jsonb(ARRAY['8-in-1','ethernet','hdmi','100w']), '{"HDMI":"4K@60Hz","Ethernet":"1Gbps","USB-A":"2x 5Gbps","USB-C":"5Gbps"}'::jsonb),
  (gen_random_uuid(), 'UGREEN Revodok USB-C 5-in-1', 'Compact 5-port USB-C hub with 4K HDMI, 100W PD, and 3 USB-A ports. Tangle-free cable design. Perfect for travel and office.', '15.99', '23.99', 'USB-C Charging Hubs', 'Hub', 'https://images.pexels.com/photos/4202315/pexels-photo-4202315.jpeg?auto=compress&cs=tinysrgb&w=600', '4.6', 189, 234, 'HUB-5N1-001', false, false, to_jsonb(ARRAY['compact','travel','hdmi','5-port']), '{"HDMI":"4K@30Hz","USB-C PD":"100W","USB-A":"3x USB 3.0","Cable":"1ft"}'::jsonb),
  (gen_random_uuid(), 'Anker PowerPort III Nano Travel Kit', 'Complete travel kit with 20W Nano charger, USB-C cable, and carrying case. Ultra-compact for any bag. Works worldwide with any USB-C device.', '12.99', '18.99', 'Travel Charging Kits', 'Travel', 'https://images.pexels.com/photos/4218883/pexels-photo-4218883.jpeg?auto=compress&cs=tinysrgb&w=600', '4.8', 234, 189, 'TCK-20W-001', true, true, to_jsonb(ARRAY['travel','20w','compact','kit']), '{"Charger":"20W Nano","Cable":"3ft USB-C","Case":"EVA","Weight":"120g"}'::jsonb),
  (gen_random_uuid(), 'Baseus Travel Adapter Pro Kit', 'Universal travel adapter with 65W GaN charger, 4 international plugs, USB-C cable, and pouch. 1 kit for 150+ countries.', '17.99', '27.99', 'Travel Charging Kits', 'Travel', 'https://images.pexels.com/photos/4792728/pexels-photo-4792728.jpeg?auto=compress&cs=tinysrgb&w=600', '4.7', 156, 145, 'TCK-65W-001', true, true, to_jsonb(ARRAY['universal','travel','65w','gan']), '{"Adapter":"150+ Countries","Charger":"65W GaN","Ports":"3","Extras":"Cable+Pouch"}'::jsonb),
  (gen_random_uuid(), 'UGREEN Travel Charger Kit', '30W travel charger with foldable plug and USB-C to Lightning cable. MFi-certified. Compact EVA case included.', '14.99', '21.99', 'Travel Charging Kits', 'Travel', 'https://images.pexels.com/photos/4041178/pexels-photo-4041178.jpeg?auto=compress&cs=tinysrgb&w=600', '4.6', 123, 234, 'TCK-30W-001', false, false, to_jsonb(ARRAY['travel','30w','mfi','foldable']), '{"Charger":"30W","Cable":"Lightning","Certification":"MFi","Case":"EVA"}'::jsonb),
  (gen_random_uuid(), 'Spigen MagSafe Ring Plate', 'Universal MagSafe-compatible metal ring plate for any phone case. Strong adhesive backing. Enables magnetic accessories for any device.', '9.99', '14.99', 'MagSafe Accessories', 'MagSafe', 'https://images.pexels.com/photos/4202315/pexels-photo-4202315.jpeg?auto=compress&cs=tinysrgb&w=600', '4.5', 89, 456, 'MSA-RNG-001', true, false, to_jsonb(ARRAY['universal','magnetic','adhesive','ring']), '{"Color":"Silver","Adhesive":"3M","Weight":"5g","Compatibility":"Any Case"}'::jsonb),
  (gen_random_uuid(), 'Anker MagGo Car Mount', 'Magnetic car mount for MagSafe iPhones. 360-degree ball joint for perfect viewing angle. Strong vent clip holds securely on any road.', '13.99', '19.99', 'MagSafe Accessories', 'MagSafe', 'https://images.pexels.com/photos/4218883/pexels-photo-4218883.jpeg?auto=compress&cs=tinysrgb&w=600', '4.7', 234, 178, 'MSA-CAR-001', true, true, to_jsonb(ARRAY['car','mount','360','magnetic']), '{"Rotation":"360°","Clip":"Vent","MagSafe":"Compatible","Weight":"80g"}'::jsonb),
  (gen_random_uuid(), 'ESR MagSafe HaloLock Stand', 'Magnetic desk stand with MagSafe compatibility. 15W charging with adjustable height and angle. Premium aluminum finish.', '15.99', '24.99', 'MagSafe Accessories', 'MagSafe', 'https://images.pexels.com/photos/4792728/pexels-photo-4792728.jpeg?auto=compress&cs=tinysrgb&w=600', '4.6', 178, 234, 'MSA-STD-001', false, true, to_jsonb(ARRAY['desk','stand','adjustable','aluminum']), '{"Charging":"15W","Height":"5-8in","Material":"Aluminum","Angle":"0-90°"}'::jsonb);
